---
abstract: 'FreeSWITCH log line processing.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0.16
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.07
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-FreeSWITCH-Line
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Error::Pure: 0.18
  Error::Pure::Always: 0.04
  Mo: 0
  Readonly: 0
  Scalar::Util: 0
  perl: 5.8.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Log-FreeSWITCH-Line
  homepage: https://github.com/tupinek/Log-FreeSWITCH-Line
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Log-FreeSWITCH-Line
version: '0.01'
